name: Test, Build and Push to Google Cloud run  


on:
  push:
    branches:
      - "18-me"
      - "main"
      - "master"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkkout code
        uses: actions/checkout@v3 
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install requirements
        run: |
          python -m pip install -r src/requirements.txt
      - name: Run tests
        env:
          MODE: "github actions"
        run: |
          pytest src/tests.py




# build_deploy:
#   needs: test
#   runs-on: ubuntu-latest