name: Google Cloud Secrets


on:
  workflow_dispatch:
  
jobs:
  update_secret:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Configure dotenv file
        run: |
          cat << EOF > .env
          MODE=${{ secrets.APP_MODE }}
          TOKEN=${{ secrets.APP_TOKEN }}
          EOF
      - name: Run a new version of secrets
        run:
          gcloud secrets versions add ${{ secrets.GCLOUD_SECRET_LABEL }} --data-file .env
      
      
